version: "3.3"

services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: webflux
      MYSQL_ROOT_PASSWORD: 1234
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  mongo:
    image: "mongo"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=reactive
      - MONGO_INITDB_ROOT_PASSWORD=1234
